[package]
name = "projext"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfonts = "1.1.0"
tts_rust = "0.3.5"
term_size = "0.3.2"
